//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YassakawaInterface {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class YASSAKAWA_SETTINGS : global::System.Configuration.ApplicationSettingsBase {
        
        private static YASSAKAWA_SETTINGS defaultInstance = ((YASSAKAWA_SETTINGS)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new YASSAKAWA_SETTINGS())));
        
        public static YASSAKAWA_SETTINGS Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ROriginalX {
            get {
                return ((double)(this["ROriginalX"]));
            }
            set {
                this["ROriginalX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ROriginalY {
            get {
                return ((double)(this["ROriginalY"]));
            }
            set {
                this["ROriginalY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ROriginalZ {
            get {
                return ((double)(this["ROriginalZ"]));
            }
            set {
                this["ROriginalZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ROriginalRX {
            get {
                return ((double)(this["ROriginalRX"]));
            }
            set {
                this["ROriginalRX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ROriginalRY {
            get {
                return ((double)(this["ROriginalRY"]));
            }
            set {
                this["ROriginalRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ROriginalRZ {
            get {
                return ((double)(this["ROriginalRZ"]));
            }
            set {
                this["ROriginalRZ"] = value;
            }
        }
    }
}
